// Generates src/icons.js from lucide-static (ISC) - deterministic subset
// of the icons this reference renders. Icon geometry is verbatim upstream.
const fs = require("node:fs");
const path = require("node:path");

const ICONS = [
  "arrow-right", // upstream button-example icon-size/inline-end specimens
  "arrow-left-circle", // upstream button-example inline-start specimen
  "check",
  "chevron-down",
  "chevron-up",
  "chevron-left",
  "chevron-right",
  "ellipsis", // lucide name for "more-horizontal"
  "x",
  "plus",
  "minus",
  "sun",
  "moon",
  "monitor",
  "bold",
  "italic",
  "underline",
  "circle-alert",
  "user",
  "settings",
  "log-out",
  // settings-nav (sidebar-13 desktop subset)
  "palette",
  "bot",
  "mic",
  "plug",
  "sliders-horizontal",
];

const dir = path.join(__dirname, "..", "node_modules", "lucide-static", "icons");
const out = { version: "1.21.0", license: "ISC", icons: {} };
for (const name of ICONS) {
  const svg = fs.readFileSync(path.join(dir, `${name}.svg`), "utf8");
  const inner = svg
    .slice(svg.indexOf(">", svg.indexOf("<svg")) + 1, svg.lastIndexOf("</svg"))
    .trim();
  out.icons[name] = inner;
}

const js =
  `// GENERATED by scripts/build-icons.js - do not edit.\n` +
  `// Lucide icon geometry, verbatim paths from lucide-static@1.21.0.\n` +
  `// ISC License - Copyright (c) Lucide Contributors -\n` +
  `// https://lucide.dev/license (see vendor/lucide notice in reference.json)\n` +
  `window.LUCIDE = ${JSON.stringify(out, null, 2)};\n` +
  `window.icon = (name, cls, dataIcon) => {\n` +
  `  const g = window.LUCIDE.icons[name];\n` +
  `  if (!g) throw new Error("unknown lucide icon: " + name);\n` +
  `  const di = dataIcon ? ' data-icon="' + dataIcon + '"' : "";\n` +
  `  return '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="' + (cls || "") + '" aria-hidden="true" data-part="icon"' + di + ">" + g + "</svg>";\n` +
  `};\n`;

fs.writeFileSync(path.join(__dirname, "..", "src", "icons.js"), js);
console.log(`icons.js: ${ICONS.length} icons`);
