// Generates vendor/shadcn/theme-neutral.css deterministically from the
// VERBATIM vendored apps/v4/registry/themes.ts (neutral entry's
// cssVars.light / cssVars.dark). reference:check re-runs this and compares
// byte-exact - the generated file must never contain local edits; local
// additions live in src/theme-local.css.
const fs = require("node:fs");
const path = require("node:path");

const ROOT = path.join(__dirname, "..");
const SRC = path.join(ROOT, "vendor/shadcn/apps/v4/registry/themes.ts");
const OUT = path.join(ROOT, "vendor/shadcn/theme-neutral.css");

function generate() {
  const src = fs.readFileSync(SRC, "utf8");
  const ni = src.indexOf('name: "neutral"');
  if (ni < 0) throw new Error('themes.ts: no "neutral" theme');
  // extract the neutral theme object by brace matching
  let start = src.lastIndexOf("{", ni);
  let depth = 0;
  let end = start;
  for (; end < src.length; end++) {
    if (src[end] === "{") depth++;
    else if (src[end] === "}") {
      depth--;
      if (depth === 0) { end++; break; }
    }
  }
  const obj = src.slice(start, end);
  const grab = (mode) => {
    const key = `${mode}: {`;
    const i = obj.indexOf(key);
    if (i < 0) throw new Error(`neutral cssVars.${mode} missing`);
    let j = i + key.length;
    let d = 1;
    const body = [];
    for (; j < obj.length; j++) {
      const c = obj[j];
      if (c === "{") d++;
      else if (c === "}") { if (--d === 0) break; }
      body.push(c);
      }
    const vars = {};
    for (const m of body.join("").matchAll(/"([^"]+)"\s*:\s*"([^"]+)"|([a-zA-Z-]+)\s*:\s*"([^"]+)"/g)) {
      const k = m[1] || m[3];
      vars[k] = m[2] || m[4];
    }
    return vars;
  };
  const light = grab("light");
  const dark = grab("dark");
  const emit = (sel, vars) => {
    // radius is emitted first like upstream's published theme css
    const keys = Object.keys(vars).filter((k) => k !== "radius");
    const head = vars.radius ? `  --radius: ${vars.radius};\n` : "";
    return `${sel} {\n${head}${keys.map((k) => `  --${k}: ${vars[k]};`).join("\n")}\n}`;
  };
  return `/* GENERATED by scripts/theme.js from the VERBATIM vendored
 * apps/v4/registry/themes.ts - theme "neutral"
 * (upstream commit 295a1f114a138f23b5dfee0e0c6812394dfeb90c).
 * Do not edit - reference:check re-derives and compares byte-exact.
 * Local additions live in src/theme-local.css. */

${emit(":root", light)}

${emit(".dark", dark)}
`;
}

const css = generate();
if (process.argv.includes("--check")) {
  const cur = fs.existsSync(OUT) ? fs.readFileSync(OUT, "utf8") : null;
  if (cur !== css) { console.error("theme-neutral.css differs from themes.ts derivation"); process.exit(1); }
  console.log("theme-neutral.css matches themes.ts derivation");
} else {
  fs.writeFileSync(OUT, css);
  console.log("theme-neutral.css regenerated");
}
